export const LINKED_IN_LINK = 'https://www.linkedin.com/in/alexander-jeam-oro/'
export const GITHUB_LINK = 'https://github.com/oroalej'
export const EMAIL_ADDRESS = 'alexanderjeamoro@gmail.com'
export const FACEBOOK_LINK = 'https://www.facebook.com/jeam.oro/'
export const TWITTER_LINK = 'https://twitter.com/oroalej'
